services:
  ine_api:
    build: ./api
    ports:
      - 5000:5000
    env_file:
      - mongo.env
    volumes:
      - ./api:/app
    environment:
      - MONGO_USERNAME=$$MONGO_INITDB_ROOT_USERNAME
      - MONGO_PASSWORD=$$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_HOST=mongodb

      - FLASK_ENV=development

  mongodb:
    image: mongo
    env_file:
      - mongo.env

